<div>
  <h1>Contáctanos</h1>
  <!-- Formulario para enviar un mensaje de contacto -->
  <form method="post" action="<?php echo $this->url('formulario'); ?>">
      <!-- Campo para ingresar el nombre -->
      <label for="nombre">Nombre:</label>
      <input type="text" id="nombre" name="nombre" required>

      <!-- Campo para ingresar el correo electrónico -->
      <label for="email">Correo electrónico:</label>
      <input type="email" id="email" name="email" required>

      <!-- Campo para ingresar el mensaje -->
      <label for="mensaje">Mensaje:</label>
      <textarea id="mensaje" name="mensaje" required></textarea>

      <!-- Botón para enviar el formulario -->
      <button type="submit">Enviar</button>
  </form>
</div>
